### ISSUE TITLE
Queue Download Requests

### ISSUE THREAD

**Issue by RowlandOti** [huxq17/Pump#12]
How best can I queue requests, one after another. I have a media application and I need the user to be able to download any no. of items on the fly like Netflix download Button. User should be able to resume the download, even if he exited the app,.

**Comment by huxq17** [comment]
I don't known what you want,I've never used Netflix.

**Comment by RowlandOti** [comment]
Forget about Netflix (confusing if you don't use it), but the feature am trying to implement is:
-  display a list of all downloads and their progress
- which should happen, even if the user had closed the app and resumed it.

**Comment by huxq17** [comment]
I will support at this weekend.

**Comment by RowlandOti** [comment]
Thanks, will appreciate that.

**Comment by huxq17** [comment]
See [RemoteDownloadListActivity](https://github.com/huxq17/Pump/blob/master/app/src/main/java/com/huxq17/download/demo/remote/RemoteDownloadListActivity.java) maybe helpful, you can install demo to experience the effect.

**Comment by RowlandOti** [comment]
Awesome! This works great for me now,  as it is the feature I wanted. Thanks for the support.
