### ISSUE TITLE
Unable to set path from getExternalStorageDirectory

### ISSUE THREAD

**Issue by skfaisal93** [huxq17/Pump#21]
Hello I have tried to set path from getExternalStorageDirectory but it always gives you following error:

`com.huxq17.download.demo E/Pump: Pump onFailed code=2001`

**Comment by huxq17** [comment]
This looks like a network error. Can you provide logcat for more error details.

**Comment by skfaisal93** [comment]
It seems that my app is not requesting run time permission that is why I am facing this issue. I have tested in the separated app and it was working fine. Sorry to bother you.
