### ISSUE TITLE
Download failed but listener doesn't notify

### ISSUE THREAD

**Issue by nana-desu** [huxq17/Pump#24]
Can you fix the listener? Download task may be killed by another service but DownloadListener doesn't notify and keep getting stuck at onProgress.

![image](https://user-images.githubusercontent.com/59090734/76136131-c49d6e00-6060-11ea-9b57-a4bdd13f2f62.jpg)

```kotlin
private var downloadListener: DownloadListener = object: DownloadListener() {
    override fun onProgress(progress: Int) {
       NotificationCompat
       ...
    }
     override fun onFailed() {  <-- status should be here
       NotificationCompat
       ...
    }

}
```

**Comment by nana-desu** [comment]
maybe duplicate #23

**Comment by nana-desu** [comment]
File sometimes return .bin, not the actual extension.

**Comment by huxq17** [comment]
extension not found will return .bin,do you know the real extension?
