### ISSUE TITLE
Pump.stop not working reliably

### ISSUE THREAD

**Issue by hashweather** [huxq17/Pump#26]
Hello, the `Pump.stop()` function to cancel a download doesn't work reliably. Even after calling the function the download still continues and the `onProgress` still fires. See below

 ```
  public static void cancelDownload(String downloadId) {
        Pump.pause(downloadId);
        Pump.stop(downloadId);
       //Download was cancelled but the onProgress(int progress) is still firing the progress of the
      //download
    }
```

Any help would be greatly appreciated.

**Comment by huxq17** [comment]
When you invoke `Pump.stop()` method,download is stopped, `onProgress()` method only receive a download info about stopped,but completed download size of file is not changed after stop. 
by the way, `Pump.pause()` is not unneccessary.
