### ISSUE TITLE
Images downloaded successfully but not able to open them/access them on Android Pie 9.0 (Xiaomi MI A2)

### ISSUE THREAD

**Issue by ramanatzoptal** [huxq17/Pump#3]
![pump](https://user-images.githubusercontent.com/38353567/49356866-32871700-f6f3-11e8-9b39-d4871a66e41d.png)

**Comment by huxq17** [comment]
It looks like the picture can't be previewed，is the picture damaged?

**Comment by huxq17** [comment]
Can you view the picture when click it?

**Comment by ramanatzoptal** [comment]
Reply 1 ) The picture was downloaded perfectly.
Reply 2 ) No I am not able to view it.
Reply 3 ) it's the ES file explorer which doesn't show prefix like the picture extension is .png
The problem is I am not able to preview it after downloading successfully in memory . 
Device Xiaomi mi A2

**Comment by huxq17** [comment]
Are you sure the file is a normal picture? Try download [this picture](http://pic1a.nipic.com/2009-01-07/20091713417344_2.jpg).

**Comment by ramanatzoptal** [comment]
Yes I'm sure because this library is working in other device like samsung A7
