### ISSUE TITLE
file:// and content:// uri app only give file:// scheme

### ISSUE THREAD

**Issue by Inside4ndroid** [huxq17/Pump#32]
Hi i have added a button into the list of downloads and when i am using android 9 or above i cannot open the file in a file manager because the library is only returning the old file:// schematic but the new android 9 and above require the content:// scheme..

any help would be apreciated

Please noet the list is downloaded video files..

**Comment by huxq17** [comment]
OK,I will resolve it at this weekend.

**Comment by huxq17** [comment]
![image](https://user-images.githubusercontent.com/11348713/87868667-e6bdda00-c9ca-11ea-9103-55d200cff1c9.png)
This method may solve your problem.

**Comment by Inside4ndroid** [comment]
it may work but i have a problem i am using java and i am struggling to convert the kotlin to java hahahaha...

**Comment by Inside4ndroid** [comment]
i have an issue i am using java and i am struggling to convert the kotlin to java hahahahaha!!

**Comment by Inside4ndroid** [comment]
i managed to do it in java BUT when trying to open the cache folder in filemanager it keeps telling me it cannot open the file??? i give up lol!!

```
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.N){
                        Intent intent = new Intent(Intent.ACTION_VIEW);
                        Uri contenturi = FileProvider.getUriForFile(DownloadListActivity.this, getPackageName()+".fileProvider-installApk", folder_location);
                        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                        DownloadListActivity.this.grantUriPermission(getPackageName(), contenturi, Intent.FLAG_GRANT_READ_URI_PERMISSION);
                        Log.d("FILE TEST ", "uri= "+contenturi);
                        intent.setDataAndType(contenturi, "*/*");
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                        startActivity(Intent.createChooser(intent, "THIS A TEST"));

                    }
```

**Comment by huxq17** [comment]
![image](https://user-images.githubusercontent.com/11348713/87876099-530afe80-ca08-11ea-8cf4-cb0d12ab3dd9.png)
I get this way to play video successfully.
